
= Quotes
:toc:
:toclevels: 2

== Seneca, "On the Shortness of Life"

* Life is long enough, and it's been given to us in generous measure for accomplishing the greatest things,
if the whole of it is well invested. But when life is squandered through soft and careless living,
and when it's spent on no worthwhile pursuit, death finally presses and we realize that
the life which we didn't notice passing has passed away.

* Just as impressive and princely wealth is squandered in an instant when it passes into the hands of a poor manager,
but wealth however modest grows through careful deployment if it is entrusted to a responsible guardian,
just so our lifetime offers ample scope to the person who maps it out well.

* So there's no reason to believe that someone has lived long because he has gray hair and wrinkles:
he's not lived long but long existed. For suppose you thought that a person had sailed far
who'd been caught in a savage storm as soon as he left harbor, and after being carried in this direction and that,
was driven in circles over the same course by alternations of the winds raging from different quarters:
he didn't have a long voyage, but he was long tossed about.

* Of all people, they alone who give their time to philosophy are at leisure, they alone really live.
For it's not just their own lifetime that they watch over carefully, but they annex every age to their own;
all the years that have gone before are added to their own.

* There is a common saying that it was not in our power to choose the parents we were allotted, and that they were given to us by chance;
yet we can be born to whomever we wish. There are households of the most distinguished intellects: choose the one into which
you'd like to be adopted, and you'll inherit not just the name but also the actual property [...].

* But for those who forget the past, disregard the present, and fear for the future, life is very brief and very troubled.

* But the time of actual enjoyment is short and fleeting, and made far shorter by their own fault;
for they desert one pleasure for another and cannot persist steadily in any one desire.

== Seneca, "Moral letters to Lucilius" (alternatively, "Letters from a Stoic")

* There are more things [...] likely to frighten us than there are to crush us; we suffer more often in imagination than in reality.

== Marcus Aurelius, "Meditations"

* The happiness of your life depends upon the quality of your thoughts.

* Reject your sense of injury and the injury itself disappears.

* Waste no more time arguing about what a good man should be. Be one.

* The best revenge is to be unlike him who performed the injury.

* I have often wondered how it is that every man loves himself more than all the rest of men,
but yet sets less value on his own opinion of himself than on the opinion of others.

* It is not death that a man should fear, but he should fear never beginning to live.

* Both the longest to live and the earliest to die suffer the same loss.

* To observe [...] what death is [...] he will then consider it to be nothing else than an operation of nature;
and if any one is afraid of an operation of nature, he is a child.

== Albert Camus, "The Myth of Sisyphus and Other Essays"

* There is but one truly serious philosophical problem, and that is suicide.
Judging whether life is or is not worth living amounts to answering the fundamental question of philosophy.

* Beginning to think is beginning to be undermined.

* The mind’s first step is to distinguish what is true from what is false.

* A man who has become conscious of The Absurd is forever bound to it.

* The Absurd enlightens me on this point: there is no future. Henceforth this is the reason for my inner freedom.

* You know the alternative:
either we are not free and God the all-powerful is responsible for evil.
Or we are free and responsible but God is not all-powerful.
All the scholastic subtleties have neither added anything to nor subtracted anything from the acuteness of this paradox.

* The struggle itself towards the heights is enough to fill a man's heart.

And, somewhat less thematically bound, but still interesting:

* A man is more a man through the things he keeps to himself than through those he says.

* Why should it be essential to love rarely in order to love much?

