
= Quotes
:toc:
:toclevels: 2

== Seneca, On The Shortness Of Life

* Life is long enough, and it's been given to us in generous measure for accomplishing the greatest things,
if the whole of it is well invested. But when life is squandered through soft and careless living,
and when it's spent on no worthwhile pursuit, death finally presses and we realize that
the life which we didn't notice passing has passed away.

* Just as impressive and princely wealth is squandered in an instant when it passes into the hands of a poor manager,
but wealth however modest grows through careful deployment if it is entrusted to a responsible guardian,
just so our lifetime offers ample scope to the person who maps it out well.

* So there's no reason to believe that someone has lived long because he has gray hair and wrinkles:
he's not lived long but long existed. For suppose you thought that a person had sailed far
who'd been caught in a savage storm as soon as he left harbor, and after being carried in this direction and that,
was driven in circles over the same course by alternations of the winds raging from different quarters:
he didn't have a long voyage, but he was long tossed about.

* Of all people, they alone who give their time to philosophy are at leisure, they alone really live.
For it's not just their own lifetime that they watch over carefully, but they annex every age to their own;
all the years that have gone before are added to their own.

* There is a common saying that it was not in our power to choose the parents we were allotted, and that they were given to us by chance;
yet we can be born to whomever we wish. There are households of the most distinguished intellects: choose the one into which
you'd like to be adopted, and you'll inherit not just the name but also the actual property _[...]_.

* But for those who forget the past, disregard the present, and fear for the future, life is very brief and very troubled.

* But the time of actual enjoyment is short and fleeting, and made far shorter by their own fault;
for they desert one pleasure for another and cannot persist steadily in any one desire.

